redmine_download_url: http://www.redmine.org/releases/redmine-4.0.5.tar.gz

# redmine_download_url: http://www.redmine.org/releases/redmine-3.4.7.tar.gz
# redmine_version: 3.4.7

# redmine_download_url: http://www.redmine.org/releases/redmine-3.3.9.tar.gz
# redmine_version: 3.3.9

redmine_lang: zh