---
- name: redmine
  hosts: redmine
  remote_user: root

  roles:
    - { role: common , tags: "common"} 
    - { role: nginx , tags: "nginx"}
    - { role: mysql , tags: "mysql"}
    - { role: redmine, tags: "redmine"}