- import_tasks: CentOS.yml
  when: ansible_distribution == 'CentOS'

- import_tasks: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'


<<<<<<< HEAD
=======
- name: Create credentials Folder
  file:
    path: /credentials
    state: directory

- name: Write Databases Password
  template:
    src: password.txt.jinja2
    dest: /credentials/password.txt
    mode: 644

>>>>>>> 950551f1bbd9378b70ecc1ad2300dbf0006fdbf7
- name: Check MySQL Version
  shell: mysql -V
  register: mysql_ver
  notify: MySQL Version


<<<<<<< HEAD
=======
    
>>>>>>> 950551f1bbd9378b70ecc1ad2300dbf0006fdbf7
